# Site settings
class:
  short: CLASS_SHORT
  link: CLASS_LINK
  long: CLASS_LONG
  term: TERM
school:
  name: SCHOOL_NAME
  link: SCHOOL_LINK
email:
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTION
baseurl: /class-projects-template/
url: http://ebrelsford.github.io
twitter_username:
github_username:  GITHUB_USERNAME

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
